os: linux
dist: xenial
sudo: required

language: cpp
compiler: gcc

cache:
    directories:
        - ${TRAVIS_BUILLD_DIR}/deps

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "JtcUeUxYQoaxJnQPmOxJiPI1Af1E6m8THXhIqrDxKo979jtvi+7TBQORQHBR+QBJ1Ux4zbvt6xnfj2tQuxVB01E+1fX3F05ZuehVrZ85jI0yaDVKuqS0bKPWJvT4kVneEnjAM34OIEaFjy0LRWYsrnen64AhI5qK9SB8Q5nkg2ShAP9rLktkA6iljH2JUM6Rmq58r/hwULkm7QtrA+06AparaEukGlrxdjYmiQRAUgj72ZUmwKPv6naJNoLgJhrsLcju7gJ4ONsEFJNvql1SC/tCKAFuncqFr0Ek4fX1SoVkcOK5r5NNHdNUIEfabG1wg1TD+zF7SO7EhNvySDu9aSPMMKpyHTMVwMvJiraf50grmiZKb2o5OAMFQLL4ZQNrqShD9NKM8D5rDu+XP+9giYgTy9kBxm+LOSe1KMKIFW21Al8jFehbbaF7pGm4z8j19ichqOBVlNtKcMIHqtpWjPXolAhJn8XN6mDCFMkqXNdApefDj9ej2kqT7Cx4/A7pOc/i+EYqUqfVSSmUvTCoQqs4yQRvE2VffvPv+X19IM2JFog5X0Ams/2Jcr/wi9y5vXJI/JfA90JOqe5dtx0zqHhQ0rmYSkPnTzSCccUuMYV7BdZOIFoSdYp82a6FUCP6bSPXpcqS/J0gLlAw3MSY0sXHJFubGnNURCIvbukFpgE="
    - MAKEFLAGS="-j 2"
    - CXX=g++
    - CC=gcc

before_install:
  # Exit immediately if the branch is the "coverity_scan" branch and the job number is not 1
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_BRANCH" == "coverity_scan" ]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 1000
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-8 1000

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libboost-all-dev
  coverity_scan:
    project:
      name: "flamewing/sorcery-xtractobb"
      description: "Tool to extract Inkle's Sorcery! OBB files"
    notification_email: flamewing.sonic@gmail.com
    build_command_prepend: "cov-configure --gcc"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - if [ "$TRAVIS_BRANCH" != "coverity_scan" ]; then .travis/script.sh; fi
  - if [ -e cov-int/scm_log.txt ] ; then cat cov-int/scm_log.txt; fi
  - if [ -e cov-int/build-log.txt ] ; then cat cov-int/build-log.txt; fi

notifications:
  email: true
  on_success: change
  on_failure: always

