name: ci-macos

on:
  push:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'

jobs:
  ci-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        generator: [make, ninja, xcode]
        include:
          - generator: make
            cmake_generator: "Unix Makefiles"
          - generator: ninja
            cmake_generator: "Ninja"
          - generator: xcode
            cmake_generator: "Xcode"
    steps:
      - name: Install dependencies
        run: |
          brew install boost make ninja
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}
        run: |
          export CC=$(which $OVERRIDE_CC)
          export CXX=$(which $OVERRIDE_CXX)
          make -j2
      - name: Test
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}
        run: |
          export CC=$(which $OVERRIDE_CC)
          export CXX=$(which $OVERRIDE_CXX)
          make test
