name: ci-macos

on:
  push:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install boost make bison flex
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: |
          export LDFLAGS="-L$(brew --prefix bison)/lib -L$(brew --prefix flex)/lib
          export CPPFLAGS="-I$(brew --prefix flex)/include
          export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$PATH"
          make -j2
      - name: Test
        run: |
          make test
